#!/usr/bin/env bash

cd "${HOME}"

# Link in files, replacing whatever's already there.
ln -fs "${HOME}/dotfiles/bash/bashrc"       "${HOME}/.bashrc"
ln -fs "${HOME}/dotfiles/bash/bash_profile" "${HOME}/.bash_profile"
ln -fs "${HOME}/dotfiles/X/Xmodmap" "${HOME}/.Xmodmap"
ln -fs "${HOME}/dotfiles/git/gitconfig"     "${HOME}/.gitconfig"
ln -fs "${HOME}/dotfiles/git/gitignore_global"     "${HOME}/.gitignore_global"
ln -fs "${HOME}/dotfiles/tmux/tmux.conf"    "${HOME}/.tmux.conf"
ln -fs "${HOME}/dotfiles/vim/vimrc"         "${HOME}/.vimrc"
ln -fs "${HOME}/dotfiles/X/Xresources"         "${HOME}/.Xresources"

# Link in directories, removing whatever's already there first.
if [ -e "${HOME}/.vim/bundle" ]; then
    rm -r "${HOME}/.vim/bundle"
fi

if [ -e "${HOME}/.config/awesome" ]; then
    ln -fs "${HOME}/dotfiles/X/awesome-rc.lua" "${HOME}/.config/awesome/rc.lua"
    ln -fs "${HOME}/dotfiles/X/awesome-battery.lua" "${HOME}/.config/awesome/battery.lua"
fi
