#!/usr/bin/env bash

set -eu

cd "${HOME}"

# Link in files, replacing whatever's already there.
ln -fs "${HOME}/dotfiles/claude/skills"         "${HOME}/.claude/skills"
ln -fs "${HOME}/dotfiles/claude/commands"         "${HOME}/.claude/commands"

ln -fs ${HOME}/dotfiles/bin/git-push-to-target ${HOME}/bin/git-push-to-target
ln -fs ${HOME}/dotfiles/bin/git-pr-target ${HOME}/bin/git-pr-target
