if [ -f /etc/profile ]; then
    # Mac OS adds additional things to the PATH.
    if [ "$(uname)" == "Darwin" ]; then
        PATH=""
    fi
    source /etc/profile
fi

[[ -s "/opt/homebrew/bin/brew" ]] && eval "$(/opt/homebrew/bin/brew shellenv)"

source $HOME/.bashrc

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
