if [ -f /etc/profile ]; then
    # Mac OS adds additional things to the PATH.
    if [ "$(uname)" == "Darwin" ]; then
        PATH=""
    fi
    source /etc/profile
fi
source $HOME/.bashrc

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
